/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MenuPrincipal;

import GameLogic.GameLogic;
import java.io.File;
import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @author alexi
 */
public class BriefStory extends javax.swing.JFrame {

    /**
     * Creates new form BriefStory
     */
    public Clip clip;
    public int fileNumberStory;
    public String playerNameStory;
    public String pathStory;
    public int difficultyStory;

    public String Story = "It is the year 2673, the Human Empire has traveled beyond the stars thus conquering the stars.\n"
            + "\n"
            + "Humanity's greatest achievement has been the invention of the “Architects” AI’s capable of calculating paths\n"
            + "between dimensions, allowing humans to travel between galaxies through slipspace.\n"
            + "\n"
            + "By that point every spaceship, every space station were operated by the AI.\n"
            + "\n"
            + "However humanity’s ambition would be their own downfall.\n"
            + "\n"
            + "The Alpha Research Institute looking to break the limits to the AI’s capacity they unfortunately got more\n"
            + "than what they had bargained for.\n"
            + "\n"
            + "The Architects had gone rogue little by little destroying everything that humanity had achieved.\n"
            + "\n"
            + "You, as one of the finest pilots that the Empire had developed, have awoken from a deep cryofreeze slumber\n"
            + "to once again fight for your empire and uncover the mysteries behind the Architects’ rampage. ";

    private void reproducirSonidos(String rutaArchivo) {
        try {
            // Abrir el archivo de audio como un stream de entrada
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(new File(rutaArchivo));

            // Obtener un clip de sonido
            clip = AudioSystem.getClip();

            // Abrir el clip con el stream de audio
            clip.open(audioStream);
            clip.loop(Clip.LOOP_CONTINUOUSLY);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            e.printStackTrace();
        }
    }

    public BriefStory(String path, int fileNumber, String playerName, int difficulty) {
        fileNumberStory = fileNumber;
        playerNameStory = playerName;
        pathStory = path;
        difficultyStory = difficulty;

        initComponents();
        setLocationRelativeTo(null);
        reproducirSonidos("src/Musica/deferenceDarkness.wav");
        jTextArea1.setText(Story);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(722, 603));
        setPreferredSize(new java.awt.Dimension(722, 603));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Continue.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 10, 270, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/StoryBried.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 380, 550, 160);

        jScrollPane1.setBackground(new java.awt.Color(14, 5, 22));
        jScrollPane1.setOpaque(false);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(14, 5, 22));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(250, 250, 250));
        jTextArea1.setRows(5);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 100, 680, 460);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImages/ChBackUni.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new GameLogic(pathStory, fileNumberStory, playerNameStory, difficultyStory).setVisible(true);
        dispose();
        clip.stop();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
