/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MenuPrincipal;

import java.io.File;
import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @author alexi
 */
public class Dificultad extends javax.swing.JFrame {

    /**
     * Creates new form Dificultad
     */
    public int fileNumberDifficulty;
    public String playerNameDifficulty;
    public String pathDifficulty;
    public Clip clip;

    private void reproducirSonidos(String rutaArchivo) {
        try {
            // Abrir el archivo de audio como un stream de entrada
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(new File(rutaArchivo));

            // Obtener un clip de sonido
            clip = AudioSystem.getClip();

            // Abrir el clip con el stream de audio
            clip.open(audioStream);
            clip.loop(Clip.LOOP_CONTINUOUSLY);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            e.printStackTrace();
        }
    }

    public Dificultad(String path, int fileNumber, String playerName) {
        pathDifficulty = path;
        fileNumberDifficulty = fileNumber;
        playerNameDifficulty = playerName;
        initComponents();
        setLocationRelativeTo(null);
        reproducirSonidos("src/Musica/MenuPrincipal.wav");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Easy = new javax.swing.JLabel();
        Normal = new javax.swing.JLabel();
        Hard = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(722, 575));
        setPreferredSize(new java.awt.Dimension(722, 575));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Difficulty.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 20, 660, 70);

        Easy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Easy.png"))); // NOI18N
        Easy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EasyMouseClicked(evt);
            }
        });
        getContentPane().add(Easy);
        Easy.setBounds(80, 160, 210, 80);

        Normal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Normal.png"))); // NOI18N
        Normal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NormalMouseClicked(evt);
            }
        });
        getContentPane().add(Normal);
        Normal.setBounds(380, 140, 300, 120);

        Hard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Hard.png"))); // NOI18N
        Hard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HardMouseClicked(evt);
            }
        });
        getContentPane().add(Hard);
        Hard.setBounds(210, 320, 310, 170);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuImages/uni.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EasyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EasyMouseClicked
        // TODO add your handling code here:
        new BriefStory(pathDifficulty, fileNumberDifficulty, playerNameDifficulty, 1).setVisible(true);
        dispose();
        clip.stop();
    }//GEN-LAST:event_EasyMouseClicked

    private void NormalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NormalMouseClicked
        // TODO add your handling code here:
        new BriefStory(pathDifficulty, fileNumberDifficulty, playerNameDifficulty, 2).setVisible(true);
        dispose();
        clip.stop();
    }//GEN-LAST:event_NormalMouseClicked

    private void HardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HardMouseClicked
        // TODO add your handling code here:
        new BriefStory(pathDifficulty, fileNumberDifficulty, playerNameDifficulty, 3).setVisible(true);
        dispose();
        clip.stop();
    }//GEN-LAST:event_HardMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Easy;
    private javax.swing.JLabel Hard;
    private javax.swing.JLabel Normal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
