package Tienda;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import GameLogic.GameLogic.personajePrincipal;
import GameLogic.GameLogic.mejorasPlayer;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @author alexi
 */
public class Tienda extends javax.swing.JFrame {

    DecimalFormat df = new DecimalFormat("#.0");
    public static boolean primeraVezTienda = true;
    /**
     * Creates new form Tienda
     *
     */
    public personajePrincipal playerMejora;
    public mejorasPlayer FrameMejoras;
    private int mejoraAtaque;
    private int mejoraDefensa;
    private int mejoraVida;
    private int mejoraVelocidadAtaque;
    private int mejoraVelocidadNave;
    private int mejoraMultAtaque;
    private int mejoraMultDefensa;
    private int mejoraMultVida;
    private Clip clip;

    private void reproducirSonidos(String rutaArchivo) {
        try {
            // Abrir el archivo de audio como un stream de entrada
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(new File(rutaArchivo));

            clip = AudioSystem.getClip();
            clip.open(audioStream);
            clip.loop(Clip.LOOP_CONTINUOUSLY);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
        }
    }

    public void update() {
        scrapLabel.setText(Double.toString(playerMejora.getScrap()));

        AtkCost.setText(Double.toString(FrameMejoras.getMejoraAtaque() * 15));
        AtkPercentCost.setText(Double.toString((Math.pow(1.32, (FrameMejoras.getMejoraMultAtaque() + 10))) + 30));
        DefCost.setText(Double.toString(FrameMejoras.getMejoraDefensa() * 20));
        DefPercentCost.setText(Double.toString((Math.pow(1.32, (FrameMejoras.getMejoraMultDefensa() + 10))) + 30));
        HpCost.setText(Double.toString(FrameMejoras.getMejoraVida() * 25));
        HpPercentCost.setText(Double.toString((Math.pow(1.32, (FrameMejoras.getMejoraMultVida() + 10))) + 30));
        AtkSpdCost.setText(Double.toString(FrameMejoras.getMejoraVelocidadAtaque() * 30));
        SpdCost.setText(Double.toString(FrameMejoras.getMejoraVelocidadNave() * 30));
    }

    public Tienda(personajePrincipal Player1, mejorasPlayer frameMejoras) {
        playerMejora = Player1;
        FrameMejoras = frameMejoras;
        initComponents();
        setLocationRelativeTo(null);

        mejoraAtaque = frameMejoras.getMejoraAtaque();
        mejoraDefensa = frameMejoras.getMejoraDefensa();
        mejoraVida = frameMejoras.getMejoraVida();
        mejoraVelocidadAtaque = frameMejoras.getMejoraVelocidadAtaque();
        mejoraVelocidadNave = frameMejoras.getMejoraVelocidadNave();
        mejoraMultAtaque = frameMejoras.getMejoraMultAtaque();
        mejoraMultDefensa = frameMejoras.getMejoraMultDefensa();
        mejoraMultVida = frameMejoras.getMejoraMultVida();

        scrapLabel.setText(Double.toString(Player1.getScrap()));
        AtkCost.setText(Double.toString(FrameMejoras.getMejoraAtaque() * 15));
        AtkPercentCost.setText(Double.toString((Math.pow(1.32, (FrameMejoras.getMejoraMultAtaque() + 10))) + 30));
        DefCost.setText(Double.toString(FrameMejoras.getMejoraDefensa() * 20));
        DefPercentCost.setText(Double.toString((Math.pow(1.32, (FrameMejoras.getMejoraMultDefensa() + 10))) + 30));
        HpCost.setText(Double.toString(FrameMejoras.getMejoraVida() * 25));
        HpPercentCost.setText(Double.toString((Math.pow(1.32, (FrameMejoras.getMejoraMultVida() + 10))) + 30));
        AtkSpdCost.setText(Double.toString(FrameMejoras.getMejoraVelocidadAtaque() * 30));
        SpdCost.setText(Double.toString(FrameMejoras.getMejoraVelocidadNave() * 30));

        System.out.println(playerMejora.getDaño());
        reproducirSonidos("src/Musica/musicaTienda.wav");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Shop = new javax.swing.JLabel();
        AtkUpgrade = new javax.swing.JButton();
        DefUpgrade = new javax.swing.JButton();
        AtkCost = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        scrapLabel = new javax.swing.JLabel();
        HpUpgrade = new javax.swing.JButton();
        AtkSpdUpgrade = new javax.swing.JButton();
        AtkPercentUpgrade = new javax.swing.JButton();
        DefPercentUpgrade = new javax.swing.JButton();
        HpPercentUpgrade = new javax.swing.JButton();
        SpdUpgrade = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        DefCost = new javax.swing.JLabel();
        HpCost = new javax.swing.JLabel();
        AtkSpdCost = new javax.swing.JLabel();
        AtkPercentCost = new javax.swing.JLabel();
        DefPercentCost = new javax.swing.JLabel();
        HpPercentCost = new javax.swing.JLabel();
        SpdCost = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setLayout(null);

        Shop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShopImages/Shop.png"))); // NOI18N
        Shop.setText("Tienda");
        jPanel1.add(Shop);
        Shop.setBounds(10, 10, 180, 70);

        AtkUpgrade.setBackground(new java.awt.Color(0, 0, 0));
        AtkUpgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShopImages/Upgrade.png"))); // NOI18N
        AtkUpgrade.setBorder(null);
        AtkUpgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtkUpgradeActionPerformed(evt);
            }
        });
        jPanel1.add(AtkUpgrade);
        AtkUpgrade.setBounds(20, 210, 80, 20);

        DefUpgrade.setBackground(new java.awt.Color(0, 0, 0));
        DefUpgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShopImages/Upgrade.png"))); // NOI18N
        DefUpgrade.setBorder(null);
        DefUpgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefUpgradeActionPerformed(evt);
            }
        });
        jPanel1.add(DefUpgrade);
        DefUpgrade.setBounds(120, 210, 82, 23);

        AtkCost.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        AtkCost.setForeground(new java.awt.Color(255, 255, 255));
        AtkCost.setText("jLabel2");
        jPanel1.add(AtkCost);
        AtkCost.setBounds(40, 80, 60, 19);

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ATK+ UP");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 190, 70, 19);

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DEF+ UP");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 190, 70, 19);

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HP+ UP");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(240, 190, 60, 19);

        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ATK% UP");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 370, 70, 19);

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DEF% UP");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(130, 370, 70, 19);

        jLabel8.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("HP% UP");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(240, 370, 60, 19);

        jLabel9.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ATK SPD+ UP");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(320, 190, 100, 19);

        jLabel10.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SPD+ UP");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(340, 370, 70, 19);

        scrapLabel.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        scrapLabel.setForeground(new java.awt.Color(255, 255, 255));
        scrapLabel.setText("jLabel11");
        jPanel1.add(scrapLabel);
        scrapLabel.setBounds(340, 20, 90, 24);

        HpUpgrade.setBackground(new java.awt.Color(0, 0, 0));
        HpUpgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShopImages/Upgrade.png"))); // NOI18N
        HpUpgrade.setBorder(null);
        HpUpgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HpUpgradeActionPerformed(evt);
            }
        });
        jPanel1.add(HpUpgrade);
        HpUpgrade.setBounds(230, 210, 82, 23);

        AtkSpdUpgrade.setBackground(new java.awt.Color(0, 0, 0));
        AtkSpdUpgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShopImages/Upgrade.png"))); // NOI18N
        AtkSpdUpgrade.setBorder(null);
        AtkSpdUpgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtkSpdUpgradeActionPerformed(evt);
            }
        });
        jPanel1.add(AtkSpdUpgrade);
        AtkSpdUpgrade.setBounds(330, 210, 80, 23);

        AtkPercentUpgrade.setBackground(new java.awt.Color(0, 0, 0));
        AtkPercentUpgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShopImages/Upgrade.png"))); // NOI18N
        AtkPercentUpgrade.setBorder(null);
        AtkPercentUpgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtkPercentUpgradeActionPerformed(evt);
            }
        });
        jPanel1.add(AtkPercentUpgrade);
        AtkPercentUpgrade.setBounds(20, 390, 82, 23);

        DefPercentUpgrade.setBackground(new java.awt.Color(0, 0, 0));
        DefPercentUpgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShopImages/Upgrade.png"))); // NOI18N
        DefPercentUpgrade.setBorder(null);
        DefPercentUpgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefPercentUpgradeActionPerformed(evt);
            }
        });
        jPanel1.add(DefPercentUpgrade);
        DefPercentUpgrade.setBounds(120, 390, 82, 23);

        HpPercentUpgrade.setBackground(new java.awt.Color(0, 0, 0));
        HpPercentUpgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShopImages/Upgrade.png"))); // NOI18N
        HpPercentUpgrade.setToolTipText("");
        HpPercentUpgrade.setBorder(null);
        HpPercentUpgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HpPercentUpgradeActionPerformed(evt);
            }
        });
        jPanel1.add(HpPercentUpgrade);
        HpPercentUpgrade.setBounds(220, 390, 82, 23);

        SpdUpgrade.setBackground(new java.awt.Color(0, 0, 0));
        SpdUpgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShopImages/Upgrade.png"))); // NOI18N
        SpdUpgrade.setBorder(null);
        SpdUpgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpdUpgradeActionPerformed(evt);
            }
        });
        jPanel1.add(SpdUpgrade);
        SpdUpgrade.setBounds(330, 390, 82, 23);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShopImages/AtkUp.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 110, 60, 76);

        DefCost.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        DefCost.setForeground(new java.awt.Color(255, 255, 255));
        DefCost.setText("jLabel2");
        jPanel1.add(DefCost);
        DefCost.setBounds(140, 80, 60, 19);

        HpCost.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        HpCost.setForeground(new java.awt.Color(255, 255, 255));
        HpCost.setText("jLabel12");
        jPanel1.add(HpCost);
        HpCost.setBounds(240, 80, 70, 19);

        AtkSpdCost.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        AtkSpdCost.setForeground(new java.awt.Color(255, 255, 255));
        AtkSpdCost.setText("jLabel13");
        jPanel1.add(AtkSpdCost);
        AtkSpdCost.setBounds(340, 80, 70, 19);

        AtkPercentCost.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        AtkPercentCost.setForeground(new java.awt.Color(255, 255, 255));
        AtkPercentCost.setText("jLabel14");
        jPanel1.add(AtkPercentCost);
        AtkPercentCost.setBounds(40, 260, 60, 19);

        DefPercentCost.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        DefPercentCost.setForeground(new java.awt.Color(255, 255, 255));
        DefPercentCost.setText("jLabel15");
        jPanel1.add(DefPercentCost);
        DefPercentCost.setBounds(140, 260, 60, 19);

        HpPercentCost.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        HpPercentCost.setForeground(new java.awt.Color(255, 255, 255));
        HpPercentCost.setText("jLabel16");
        jPanel1.add(HpPercentCost);
        HpPercentCost.setBounds(230, 260, 70, 19);

        SpdCost.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        SpdCost.setForeground(new java.awt.Color(255, 255, 255));
        SpdCost.setText("jLabel17");
        jPanel1.add(SpdCost);
        SpdCost.setBounds(340, 260, 60, 19);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShopImages/AtkPercent.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 300, 60, 64);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShopImages/DefUp.png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(130, 120, 70, 70);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShopImages/HpUp.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(230, 120, 70, 64);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShopImages/AtkSpd.png"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(330, 110, 70, 90);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShopImages/DefPercent.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(130, 300, 70, 80);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShopImages/HpPercent.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(230, 300, 70, 70);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShopImages/MoveUp.png"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(330, 300, 70, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShopImages/Scrap.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 10, 250, 70);

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Close Shop");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(150, 420, 120, 22);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShopImages/Background2.jpg"))); // NOI18N
        jPanel1.add(Background);
        Background.setBounds(0, 0, 440, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtkUpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtkUpgradeActionPerformed
        System.out.println(FrameMejoras.getMejoraAtaque() + " en tienda");
        if (playerMejora.getScrap() >= (FrameMejoras.getMejoraAtaque() * 15)) {
            playerMejora.setDaño(2);
            playerMejora.setDaño();
            playerMejora.setScrap(-FrameMejoras.getMejoraAtaque() * 15);
            FrameMejoras.setMejoraAtaque();
            update();
        }
    }//GEN-LAST:event_AtkUpgradeActionPerformed

    private void DefUpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefUpgradeActionPerformed
        if (playerMejora.getScrap() >= (FrameMejoras.getMejoraDefensa() * 20)) {
            playerMejora.setDefensa(1);
            playerMejora.setDefensa();
            playerMejora.setScrap(-FrameMejoras.getMejoraDefensa() * 20);
            FrameMejoras.setMejoraDefensa();
            update();
        }

    }//GEN-LAST:event_DefUpgradeActionPerformed

    private void HpUpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HpUpgradeActionPerformed
        if (playerMejora.getScrap() >= (FrameMejoras.getMejoraVida() * 25)) {
            playerMejora.setVida(3);
            playerMejora.setVida();
            playerMejora.setScrap(-FrameMejoras.getMejoraVida() * 25);
            FrameMejoras.setMejoraVida();
            update();
        }
    }//GEN-LAST:event_HpUpgradeActionPerformed

    private void AtkPercentUpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtkPercentUpgradeActionPerformed
        if (playerMejora.getScrap() >= (Math.pow(1.32, (int) (FrameMejoras.getMejoraMultAtaque() + 10))) + 30) {
            playerMejora.setMultiplicadorDaño(0.15);
            playerMejora.setScrap(-((Math.pow(1.32, (FrameMejoras.getMejoraMultAtaque() + 10))) + 30));
            FrameMejoras.getMejoraMultAtaque();
            update();
        }
    }//GEN-LAST:event_AtkPercentUpgradeActionPerformed

    private void DefPercentUpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefPercentUpgradeActionPerformed
        if (playerMejora.getScrap() >= (Math.pow(1.32, (int) (FrameMejoras.getMejoraMultDefensa() + 10))) + 30) {
            playerMejora.setMultiplicadorDefensa(0.20);
            playerMejora.setScrap(-((Math.pow(1.32, (FrameMejoras.getMejoraMultDefensa() + 10))) + 30));
            FrameMejoras.getMejoraMultDefensa();
            update();
        }
    }//GEN-LAST:event_DefPercentUpgradeActionPerformed

    private void HpPercentUpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HpPercentUpgradeActionPerformed
        if (playerMejora.getScrap() >= (Math.pow(1.32, (FrameMejoras.getMejoraMultVida() + 10))) + 30) {
            playerMejora.setMultiplicadorVida(0.5);
            playerMejora.setScrap(-((Math.pow(1.32, (FrameMejoras.getMejoraMultVida() + 10))) + 30));
            FrameMejoras.getMejoraMultVida();
            update();
        }
    }//GEN-LAST:event_HpPercentUpgradeActionPerformed

    private void AtkSpdUpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtkSpdUpgradeActionPerformed
        if (playerMejora.getScrap() >= (FrameMejoras.getMejoraVelocidadAtaque() * 30)) {
            playerMejora.setVelocidadAtaque(30);
            playerMejora.setVelocidadAtaque();
            playerMejora.setScrap(-(FrameMejoras.getMejoraVelocidadAtaque()* 30));
            FrameMejoras.getMejoraVelocidadAtaque();
            update();
        }
    }//GEN-LAST:event_AtkSpdUpgradeActionPerformed

    private void SpdUpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpdUpgradeActionPerformed
        if (playerMejora.getScrap() >= (FrameMejoras.getMejoraVelocidadNave() * 30)) {
            playerMejora.setVelocidadNave(0.01);
            playerMejora.setVelocidadNave();
            playerMejora.setScrap(-(FrameMejoras.getMejoraVelocidadNave() * 30));
            FrameMejoras.getMejoraVelocidadNave();
            update();
        }
    }//GEN-LAST:event_SpdUpgradeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clip.stop();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        clip.stop();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AtkCost;
    private javax.swing.JLabel AtkPercentCost;
    private javax.swing.JButton AtkPercentUpgrade;
    private javax.swing.JLabel AtkSpdCost;
    private javax.swing.JButton AtkSpdUpgrade;
    private javax.swing.JButton AtkUpgrade;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel DefCost;
    private javax.swing.JLabel DefPercentCost;
    private javax.swing.JButton DefPercentUpgrade;
    private javax.swing.JButton DefUpgrade;
    private javax.swing.JLabel HpCost;
    private javax.swing.JLabel HpPercentCost;
    private javax.swing.JButton HpPercentUpgrade;
    private javax.swing.JButton HpUpgrade;
    private javax.swing.JLabel Shop;
    private javax.swing.JLabel SpdCost;
    private javax.swing.JButton SpdUpgrade;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel scrapLabel;
    // End of variables declaration//GEN-END:variables
}
